export default [
  [
    'Ford',
    'Model T',
    'Model A',
    'Model B',
    'Lincoln-Zephyr',
    'Thunderbird',
    'Falcon',
    'Mustang II',
    'Sierra',
    'Fusion',
    'Mondeo',
  ],
  [
    'BMC',
    'Austin Farina',
    'Morris Marina',
    'Austin Allegro',
    'Austin Sports',
    'Austin Lancer',
    'Morris Marshal',
    'Austin Allegro',
    'Austin Maxi',
    'Austin Maestro',
    'Morris Isis',
  ],
  ['Chevrolet', 'Bel Air', 'Blazer', 'Camaro', 'Corvette', 'Fleetline', 'Lacetti', 'Niva', 'Spark', 'Tracker', 'Viva'],
  ['BMW', 'Dixi', '501', 'Isetta', '700', '1600 GT', '1602', 'Е28', 'Е30 M3', 'E39', 'E82'],
  ['Toyota', 'Crown', 'Corolla', 'Century', 'Supra', 'Camry', 'Prius', 'Levin GT', 'Allion', 'Copen GR Sport', 'Mirai'],
  ['Nissan', 'GT-R', 'Sentra', 'Altima', 'Elgrand', 'Note', 'Leaf', 'Ariya', 'Qashqai', 'Sylphy', 'Almera'],
  ['Renault', 'Rafale', 'Captur', 'Mégane', 'Zoe', 'Twingo', 'Sandero', 'Kardian', 'Lutecia', 'Taliant', 'Arkana'],
  [
    'Pontiac',
    'Series 6-27',
    'Chieftain',
    'Bonneville',
    'Grand Am',
    'Astre',
    'Firebird',
    'Grand Prix',
    'GTO',
    'G6',
    'Chieftain',
  ],
  ['Mercedes', '300SL', '280SL', '250SL', '350SL', '450SLC', '450SEC', '190E', 'A209', 'C209', 'C218'],
  [
    'Lada',
    'Niva Legend',
    'Niva Travel',
    'Granta',
    'Largus',
    'Vesta',
    'Classic',
    'Samara',
    'Kalina',
    'Granta',
    'X-Cross 5',
  ],
];
